//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ebooks_db
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ebooks_db()
        {
            this.EBook_Review_db = new HashSet<EBook_Review_db>();
            this.Reading_History = new HashSet<Reading_History>();
        }
    
        public int Ebook_id { get; set; }
        public string Ebook_name { get; set; }
        public string Ebook_publisher { get; set; }
        public string Ebook_author { get; set; }
        public int cat_id { get; set; }
        public string Ebook_img { get; set; }
        public string Ebook_pdffile { get; set; }
        public string Ebook_edition { get; set; }
        public int mem_id { get; set; }
    
        public virtual Book_categoryy Book_categoryy { get; set; }
        public virtual tbl_member tbl_member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBook_Review_db> EBook_Review_db { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reading_History> Reading_History { get; set; }
    }
}
