//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class EBook_Review_db
    {
        public int EReview_id { get; set; }
        [AllowHtml]
        public string ContentC { get; set; }
        public double ERating { get; set; }
        public System.DateTime DatePost { get; set; }
        public int EBookId { get; set; }
        public int memberId { get; set; }
    
        public virtual Ebooks_db Ebooks_db { get; set; }
        public virtual tbl_member tbl_member { get; set; }
    }
}
