//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lastDbEntities : DbContext
    {
        public lastDbEntities()
            : base("name=lastDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book_categoryy> Book_categoryy { get; set; }
        public virtual DbSet<Tbl_admin> Tbl_admin { get; set; }
        public virtual DbSet<Tbl_Vendorr> Tbl_Vendorr { get; set; }
        public virtual DbSet<BTransaction> BTransactions { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Book_Review> Book_Review { get; set; }
        public virtual DbSet<Ebooks_db> Ebooks_db { get; set; }
        public virtual DbSet<EBook_Review_db> EBook_Review_db { get; set; }
        public virtual DbSet<Reading_History> Reading_History { get; set; }
        public virtual DbSet<tbl_wishlist> tbl_wishlist { get; set; }
        public virtual DbSet<Tbl_Books> Tbl_Books { get; set; }
        public virtual DbSet<tbl_follow> tbl_follow { get; set; }
        public virtual DbSet<tbl_subscribe> tbl_subscribe { get; set; }
        public virtual DbSet<tbl_cmnts> tbl_cmnts { get; set; }
        public virtual DbSet<tbl_contactus> tbl_contactus { get; set; }
        public virtual DbSet<tbl_group> tbl_group { get; set; }
        public virtual DbSet<tbl_groupmem> tbl_groupmem { get; set; }
        public virtual DbSet<tbl_blog> tbl_blog { get; set; }
        public virtual DbSet<tbl_member> tbl_member { get; set; }
    }
}
