//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reading_History
    {
        public int Read_Hist_Id { get; set; }
        public System.DateTime Read_Date { get; set; }
        public int memID { get; set; }
        public int ebook_id { get; set; }
    
        public virtual Ebooks_db Ebooks_db { get; set; }
        public virtual tbl_member tbl_member { get; set; }
    }
}
