//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_contactus
    {
        public int contactus_id { get; set; }
        public System.DateTime contactys_datetime { get; set; }
        public string contactus_email { get; set; }
        public string contactus_content { get; set; }
    }
}
