//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_wishlist
    {
        public int Wish_Id { get; set; }
        public int Book_ID { get; set; }
        public int mem_Id { get; set; }
        public System.DateTime Wish_date { get; set; }
    
        public virtual Tbl_Books Tbl_Books { get; set; }
        public virtual tbl_member tbl_member { get; set; }
    }
}
