//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_groupmem
    {
        public int group_mem_id { get; set; }
        public int group_mem_groupid { get; set; }
        public int group_mem_memid { get; set; }
        public System.DateTime group_mem_joindate { get; set; }
    
        public virtual tbl_group tbl_group { get; set; }
        public virtual tbl_member tbl_member { get; set; }
    }
}
