//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cmnts
    {
        public int cmnts_id { get; set; }
        public int cmnts_createdby { get; set; }
        public System.DateTime cmnts_datetime { get; set; }
        public string cmnts_content { get; set; }
        public int cmnts_blogid { get; set; }
    
        public virtual tbl_blog tbl_blog { get; set; }
        public virtual tbl_member tbl_member { get; set; }
    }
}
